services:
  mongo1:
    image: mongodb/mongodb-community-server:8.0.29-ubi9-slim
    container_name: mongodb-lesson-09-1
    hostname: mongo1

    ports:
      - "27025:27017"

    command:
      - --replSet
      - rs0

    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongodb/mongodb-community-server:8.0.29-ubi9-slim
    container_name: mongodb-lesson-09-2
    hostname: mongo2

    ports:
      - "27026:27017"

    command:
      - --replSet
      - rs0

    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongodb/mongodb-community-server:8.0.29-ubi9-slim
    container_name: mongodb-lesson-09-3
    hostname: mongo3

    ports:
      - "27027:27017"

    command:
      - --replSet
      - rs0

    volumes:
      - mongo3_data:/data/db

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data: