services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0.29-ubi9-slim
    container_name: mongodb-lesson-04
    ports:
      - "27020:27017"
    volumes:
      - mongodb_lesson_04_data:/data/db

volumes:
  mongodb_lesson_04_data: