services:
  mongodb:
    image: mongodb/mongodb-community-server:8.0.29-ubi9-slim
    container_name: mongodb-lesson-07
    ports:
      - "27023:27017"
    volumes:
      - mongodb_lesson_07_data:/data/db

volumes:
  mongodb_lesson_07_data: